apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: udagram-api-user
        imagePullPolicy: Always
        image: antema/udagram-api-user:latest
        envFrom:
        - secretRef:
            name: env-configmap-secret
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: aws-secret
